// Code generated by MockGen. DO NOT EDIT.
// Source: scenario.go
//
// Generated by this command:
//
//	mockgen -source=scenario.go -destination=mocks/scenario_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	scenario "demo_bot/internal/app/services/bot/scenario"
	reflect "reflect"

	maxbot "github.com/max-messenger/max-bot-api-client-go/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockAPI is a mock of API interface.
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
	isgomock struct{}
}

// MockAPIMockRecorder is the mock recorder for MockAPI.
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance.
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// Client mocks base method.
func (m *MockAPI) Client() *maxbot.Api {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Client")
	ret0, _ := ret[0].(*maxbot.Api)
	return ret0
}

// Client indicates an expected call of Client.
func (mr *MockAPIMockRecorder) Client() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Client", reflect.TypeOf((*MockAPI)(nil).Client))
}

// MockScenario is a mock of Scenario interface.
type MockScenario struct {
	ctrl     *gomock.Controller
	recorder *MockScenarioMockRecorder
	isgomock struct{}
}

// MockScenarioMockRecorder is the mock recorder for MockScenario.
type MockScenarioMockRecorder struct {
	mock *MockScenario
}

// NewMockScenario creates a new mock instance.
func NewMockScenario(ctrl *gomock.Controller) *MockScenario {
	mock := &MockScenario{ctrl: ctrl}
	mock.recorder = &MockScenarioMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScenario) EXPECT() *MockScenarioMockRecorder {
	return m.recorder
}

// ChatType mocks base method.
func (m *MockScenario) ChatType() scenario.ChatType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatType")
	ret0, _ := ret[0].(scenario.ChatType)
	return ret0
}

// ChatType indicates an expected call of ChatType.
func (mr *MockScenarioMockRecorder) ChatType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatType", reflect.TypeOf((*MockScenario)(nil).ChatType))
}

// Description mocks base method.
func (m *MockScenario) Description() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Description")
	ret0, _ := ret[0].(string)
	return ret0
}

// Description indicates an expected call of Description.
func (mr *MockScenarioMockRecorder) Description() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Description", reflect.TypeOf((*MockScenario)(nil).Description))
}

// Handle mocks base method.
func (m *MockScenario) Handle(ctx context.Context, p scenario.Params, s *scenario.State) (*scenario.State, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, p, s)
	ret0, _ := ret[0].(*scenario.State)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockScenarioMockRecorder) Handle(ctx, p, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockScenario)(nil).Handle), ctx, p, s)
}

// Name mocks base method.
func (m *MockScenario) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockScenarioMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockScenario)(nil).Name))
}

// RequiredPermissions mocks base method.
func (m *MockScenario) RequiredPermissions() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequiredPermissions")
	ret0, _ := ret[0].([]string)
	return ret0
}

// RequiredPermissions indicates an expected call of RequiredPermissions.
func (mr *MockScenarioMockRecorder) RequiredPermissions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequiredPermissions", reflect.TypeOf((*MockScenario)(nil).RequiredPermissions))
}

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// ClearState mocks base method.
func (m *MockStore) ClearState(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearState", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearState indicates an expected call of ClearState.
func (mr *MockStoreMockRecorder) ClearState(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearState", reflect.TypeOf((*MockStore)(nil).ClearState), ctx, userID)
}

// GetState mocks base method.
func (m *MockStore) GetState(ctx context.Context, userID int64) (*scenario.State, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetState", ctx, userID)
	ret0, _ := ret[0].(*scenario.State)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetState indicates an expected call of GetState.
func (mr *MockStoreMockRecorder) GetState(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetState", reflect.TypeOf((*MockStore)(nil).GetState), ctx, userID)
}

// SetState mocks base method.
func (m *MockStore) SetState(ctx context.Context, userID int64, state *scenario.State) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetState", ctx, userID, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetState indicates an expected call of SetState.
func (mr *MockStoreMockRecorder) SetState(ctx, userID, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetState", reflect.TypeOf((*MockStore)(nil).SetState), ctx, userID, state)
}
