// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/max-messenger/max-bot-api-client-go/v2 (interfaces: BotsAPI)
//
// Generated by this command:
//
//	mockgen -destination=internal/app/services/bot/mocks/bots_api_mock.go -package=mocks github.com/max-messenger/max-bot-api-client-go/v2 BotsAPI
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/max-messenger/max-bot-api-client-go/v2/model"
	gomock "go.uber.org/mock/gomock"
)

// MockBotsAPI is a mock of BotsAPI interface.
type MockBotsAPI struct {
	ctrl     *gomock.Controller
	recorder *MockBotsAPIMockRecorder
	isgomock struct{}
}

// MockBotsAPIMockRecorder is the mock recorder for MockBotsAPI.
type MockBotsAPIMockRecorder struct {
	mock *MockBotsAPI
}

// NewMockBotsAPI creates a new mock instance.
func NewMockBotsAPI(ctrl *gomock.Controller) *MockBotsAPI {
	mock := &MockBotsAPI{ctrl: ctrl}
	mock.recorder = &MockBotsAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBotsAPI) EXPECT() *MockBotsAPIMockRecorder {
	return m.recorder
}

// EditMyInfo mocks base method.
func (m *MockBotsAPI) EditMyInfo(ctx context.Context, patch model.BotPatch) (model.BotInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditMyInfo", ctx, patch)
	ret0, _ := ret[0].(model.BotInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditMyInfo indicates an expected call of EditMyInfo.
func (mr *MockBotsAPIMockRecorder) EditMyInfo(ctx, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditMyInfo", reflect.TypeOf((*MockBotsAPI)(nil).EditMyInfo), ctx, patch)
}

// GetMyInfo mocks base method.
func (m *MockBotsAPI) GetMyInfo(ctx context.Context) (model.BotInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyInfo", ctx)
	ret0, _ := ret[0].(model.BotInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyInfo indicates an expected call of GetMyInfo.
func (mr *MockBotsAPIMockRecorder) GetMyInfo(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyInfo", reflect.TypeOf((*MockBotsAPI)(nil).GetMyInfo), ctx)
}
