// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/max-messenger/max-bot-api-client-go/v2 (interfaces: ChatsAPI)
//
// Generated by this command:
//
//	mockgen -destination=internal/app/services/bot/mocks/chats_api_mock.go -package=mocks github.com/max-messenger/max-bot-api-client-go/v2 ChatsAPI
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/max-messenger/max-bot-api-client-go/v2/model"
	gomock "go.uber.org/mock/gomock"
)

// MockChatsAPI is a mock of ChatsAPI interface.
type MockChatsAPI struct {
	ctrl     *gomock.Controller
	recorder *MockChatsAPIMockRecorder
	isgomock struct{}
}

// MockChatsAPIMockRecorder is the mock recorder for MockChatsAPI.
type MockChatsAPIMockRecorder struct {
	mock *MockChatsAPI
}

// NewMockChatsAPI creates a new mock instance.
func NewMockChatsAPI(ctrl *gomock.Controller) *MockChatsAPI {
	mock := &MockChatsAPI{ctrl: ctrl}
	mock.recorder = &MockChatsAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatsAPI) EXPECT() *MockChatsAPIMockRecorder {
	return m.recorder
}

// AddMembers mocks base method.
func (m *MockChatsAPI) AddMembers(ctx context.Context, chatID int64, userIDs []int64) (model.SimpleQueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMembers", ctx, chatID, userIDs)
	ret0, _ := ret[0].(model.SimpleQueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddMembers indicates an expected call of AddMembers.
func (mr *MockChatsAPIMockRecorder) AddMembers(ctx, chatID, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMembers", reflect.TypeOf((*MockChatsAPI)(nil).AddMembers), ctx, chatID, userIDs)
}

// DeleteAdmins mocks base method.
func (m *MockChatsAPI) DeleteAdmins(ctx context.Context, chatID, userID int64) (model.SimpleQueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAdmins", ctx, chatID, userID)
	ret0, _ := ret[0].(model.SimpleQueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAdmins indicates an expected call of DeleteAdmins.
func (mr *MockChatsAPIMockRecorder) DeleteAdmins(ctx, chatID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAdmins", reflect.TypeOf((*MockChatsAPI)(nil).DeleteAdmins), ctx, chatID, userID)
}

// DeleteChat mocks base method.
func (m *MockChatsAPI) DeleteChat(ctx context.Context, chatID int64) (model.SimpleQueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChat", ctx, chatID)
	ret0, _ := ret[0].(model.SimpleQueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteChat indicates an expected call of DeleteChat.
func (mr *MockChatsAPIMockRecorder) DeleteChat(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChat", reflect.TypeOf((*MockChatsAPI)(nil).DeleteChat), ctx, chatID)
}

// EditChat mocks base method.
func (m *MockChatsAPI) EditChat(ctx context.Context, chatID int64, patch model.ChatPatch) (model.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditChat", ctx, chatID, patch)
	ret0, _ := ret[0].(model.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditChat indicates an expected call of EditChat.
func (mr *MockChatsAPIMockRecorder) EditChat(ctx, chatID, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditChat", reflect.TypeOf((*MockChatsAPI)(nil).EditChat), ctx, chatID, patch)
}

// GetAdmins mocks base method.
func (m *MockChatsAPI) GetAdmins(ctx context.Context, chatID int64) (model.ChatMembersList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdmins", ctx, chatID)
	ret0, _ := ret[0].(model.ChatMembersList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdmins indicates an expected call of GetAdmins.
func (mr *MockChatsAPIMockRecorder) GetAdmins(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdmins", reflect.TypeOf((*MockChatsAPI)(nil).GetAdmins), ctx, chatID)
}

// GetChat mocks base method.
func (m *MockChatsAPI) GetChat(ctx context.Context, chatID int64) (model.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChat", ctx, chatID)
	ret0, _ := ret[0].(model.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChat indicates an expected call of GetChat.
func (mr *MockChatsAPIMockRecorder) GetChat(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChat", reflect.TypeOf((*MockChatsAPI)(nil).GetChat), ctx, chatID)
}

// GetMembers mocks base method.
func (m *MockChatsAPI) GetMembers(ctx context.Context, chatID, marker, count int64, userIDs []int64) (model.ChatMembersList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembers", ctx, chatID, marker, count, userIDs)
	ret0, _ := ret[0].(model.ChatMembersList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembers indicates an expected call of GetMembers.
func (mr *MockChatsAPIMockRecorder) GetMembers(ctx, chatID, marker, count, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembers", reflect.TypeOf((*MockChatsAPI)(nil).GetMembers), ctx, chatID, marker, count, userIDs)
}

// GetMembership mocks base method.
func (m *MockChatsAPI) GetMembership(ctx context.Context, chatID int64) (model.ChatMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembership", ctx, chatID)
	ret0, _ := ret[0].(model.ChatMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembership indicates an expected call of GetMembership.
func (mr *MockChatsAPIMockRecorder) GetMembership(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembership", reflect.TypeOf((*MockChatsAPI)(nil).GetMembership), ctx, chatID)
}

// GetPinnedMessage mocks base method.
func (m *MockChatsAPI) GetPinnedMessage(ctx context.Context, chatID int64) (model.GetPinnedMessageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPinnedMessage", ctx, chatID)
	ret0, _ := ret[0].(model.GetPinnedMessageResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPinnedMessage indicates an expected call of GetPinnedMessage.
func (mr *MockChatsAPIMockRecorder) GetPinnedMessage(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPinnedMessage", reflect.TypeOf((*MockChatsAPI)(nil).GetPinnedMessage), ctx, chatID)
}

// LeaveChat mocks base method.
func (m *MockChatsAPI) LeaveChat(ctx context.Context, chatID int64) (model.SimpleQueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LeaveChat", ctx, chatID)
	ret0, _ := ret[0].(model.SimpleQueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LeaveChat indicates an expected call of LeaveChat.
func (mr *MockChatsAPIMockRecorder) LeaveChat(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeaveChat", reflect.TypeOf((*MockChatsAPI)(nil).LeaveChat), ctx, chatID)
}

// PinMessage mocks base method.
func (m *MockChatsAPI) PinMessage(ctx context.Context, chatID int64, messageID string, notify bool) (model.SimpleQueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PinMessage", ctx, chatID, messageID, notify)
	ret0, _ := ret[0].(model.SimpleQueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PinMessage indicates an expected call of PinMessage.
func (mr *MockChatsAPIMockRecorder) PinMessage(ctx, chatID, messageID, notify any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PinMessage", reflect.TypeOf((*MockChatsAPI)(nil).PinMessage), ctx, chatID, messageID, notify)
}

// RemoveMember mocks base method.
func (m *MockChatsAPI) RemoveMember(ctx context.Context, chatID, userID int64, block bool) (model.SimpleQueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, chatID, userID, block)
	ret0, _ := ret[0].(model.SimpleQueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockChatsAPIMockRecorder) RemoveMember(ctx, chatID, userID, block any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockChatsAPI)(nil).RemoveMember), ctx, chatID, userID, block)
}

// SendAction mocks base method.
func (m *MockChatsAPI) SendAction(ctx context.Context, chatID int64, action model.SenderAction) (model.SimpleQueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAction", ctx, chatID, action)
	ret0, _ := ret[0].(model.SimpleQueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendAction indicates an expected call of SendAction.
func (mr *MockChatsAPIMockRecorder) SendAction(ctx, chatID, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAction", reflect.TypeOf((*MockChatsAPI)(nil).SendAction), ctx, chatID, action)
}

// SetAdmins mocks base method.
func (m *MockChatsAPI) SetAdmins(ctx context.Context, chatID int64, admins []model.ChatAdmin) (model.SimpleQueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAdmins", ctx, chatID, admins)
	ret0, _ := ret[0].(model.SimpleQueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetAdmins indicates an expected call of SetAdmins.
func (mr *MockChatsAPIMockRecorder) SetAdmins(ctx, chatID, admins any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAdmins", reflect.TypeOf((*MockChatsAPI)(nil).SetAdmins), ctx, chatID, admins)
}

// UnpinMessage mocks base method.
func (m *MockChatsAPI) UnpinMessage(ctx context.Context, chatID int64) (model.SimpleQueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnpinMessage", ctx, chatID)
	ret0, _ := ret[0].(model.SimpleQueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnpinMessage indicates an expected call of UnpinMessage.
func (mr *MockChatsAPIMockRecorder) UnpinMessage(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpinMessage", reflect.TypeOf((*MockChatsAPI)(nil).UnpinMessage), ctx, chatID)
}
