// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/max-messenger/max-bot-api-client-go/v2 (interfaces: MessagesAPI)
//
// Generated by this command:
//
//	mockgen -destination=internal/app/services/bot/mocks/messages_api_mock.go -package=mocks github.com/max-messenger/max-bot-api-client-go/v2 MessagesAPI
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	v2 "github.com/max-messenger/max-bot-api-client-go/v2"
	model "github.com/max-messenger/max-bot-api-client-go/v2/model"
	gomock "go.uber.org/mock/gomock"
)

// MockMessagesAPI is a mock of MessagesAPI interface.
type MockMessagesAPI struct {
	ctrl     *gomock.Controller
	recorder *MockMessagesAPIMockRecorder
	isgomock struct{}
}

// MockMessagesAPIMockRecorder is the mock recorder for MockMessagesAPI.
type MockMessagesAPIMockRecorder struct {
	mock *MockMessagesAPI
}

// NewMockMessagesAPI creates a new mock instance.
func NewMockMessagesAPI(ctrl *gomock.Controller) *MockMessagesAPI {
	mock := &MockMessagesAPI{ctrl: ctrl}
	mock.recorder = &MockMessagesAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessagesAPI) EXPECT() *MockMessagesAPIMockRecorder {
	return m.recorder
}

// AnswerOnCallback mocks base method.
func (m *MockMessagesAPI) AnswerOnCallback(ctx context.Context, callbackID string, answer model.CallbackAnswer) (model.SimpleQueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerOnCallback", ctx, callbackID, answer)
	ret0, _ := ret[0].(model.SimpleQueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnswerOnCallback indicates an expected call of AnswerOnCallback.
func (mr *MockMessagesAPIMockRecorder) AnswerOnCallback(ctx, callbackID, answer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerOnCallback", reflect.TypeOf((*MockMessagesAPI)(nil).AnswerOnCallback), ctx, callbackID, answer)
}

// DeleteMessage mocks base method.
func (m *MockMessagesAPI) DeleteMessage(ctx context.Context, messageID string) (model.SimpleQueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessage", ctx, messageID)
	ret0, _ := ret[0].(model.SimpleQueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMessage indicates an expected call of DeleteMessage.
func (mr *MockMessagesAPIMockRecorder) DeleteMessage(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessage", reflect.TypeOf((*MockMessagesAPI)(nil).DeleteMessage), ctx, messageID)
}

// EditMessage mocks base method.
func (m *MockMessagesAPI) EditMessage(ctx context.Context, messageID string, body model.NewMessageBody) (model.SimpleQueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditMessage", ctx, messageID, body)
	ret0, _ := ret[0].(model.SimpleQueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditMessage indicates an expected call of EditMessage.
func (mr *MockMessagesAPIMockRecorder) EditMessage(ctx, messageID, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditMessage", reflect.TypeOf((*MockMessagesAPI)(nil).EditMessage), ctx, messageID, body)
}

// GetMessageByID mocks base method.
func (m *MockMessagesAPI) GetMessageByID(ctx context.Context, messageID string) (model.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageByID", ctx, messageID)
	ret0, _ := ret[0].(model.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageByID indicates an expected call of GetMessageByID.
func (mr *MockMessagesAPIMockRecorder) GetMessageByID(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageByID", reflect.TypeOf((*MockMessagesAPI)(nil).GetMessageByID), ctx, messageID)
}

// GetMessages mocks base method.
func (m *MockMessagesAPI) GetMessages(ctx context.Context, chatID, from, to, count int64, messageIDs []string) (model.MessageList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessages", ctx, chatID, from, to, count, messageIDs)
	ret0, _ := ret[0].(model.MessageList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessages indicates an expected call of GetMessages.
func (mr *MockMessagesAPIMockRecorder) GetMessages(ctx, chatID, from, to, count, messageIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessages", reflect.TypeOf((*MockMessagesAPI)(nil).GetMessages), ctx, chatID, from, to, count, messageIDs)
}

// GetVideoAttachmentDetails mocks base method.
func (m *MockMessagesAPI) GetVideoAttachmentDetails(ctx context.Context, videoToken string) (model.VideoAttachmentDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideoAttachmentDetails", ctx, videoToken)
	ret0, _ := ret[0].(model.VideoAttachmentDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVideoAttachmentDetails indicates an expected call of GetVideoAttachmentDetails.
func (mr *MockMessagesAPIMockRecorder) GetVideoAttachmentDetails(ctx, videoToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideoAttachmentDetails", reflect.TypeOf((*MockMessagesAPI)(nil).GetVideoAttachmentDetails), ctx, videoToken)
}

// Send mocks base method.
func (m *MockMessagesAPI) Send(ctx context.Context, msg *v2.Message) (model.SendMessageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, msg)
	ret0, _ := ret[0].(model.SendMessageResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockMessagesAPIMockRecorder) Send(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockMessagesAPI)(nil).Send), ctx, msg)
}
