// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/max-messenger/max-bot-api-client-go/v2 (interfaces: UploadAPI)
//
// Generated by this command:
//
//	mockgen -destination=internal/app/services/bot/mocks/upload_api_mock.go -package=mocks github.com/max-messenger/max-bot-api-client-go/v2 UploadAPI
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	model "github.com/max-messenger/max-bot-api-client-go/v2/model"
	gomock "go.uber.org/mock/gomock"
)

// MockUploadAPI is a mock of UploadAPI interface.
type MockUploadAPI struct {
	ctrl     *gomock.Controller
	recorder *MockUploadAPIMockRecorder
	isgomock struct{}
}

// MockUploadAPIMockRecorder is the mock recorder for MockUploadAPI.
type MockUploadAPIMockRecorder struct {
	mock *MockUploadAPI
}

// NewMockUploadAPI creates a new mock instance.
func NewMockUploadAPI(ctrl *gomock.Controller) *MockUploadAPI {
	mock := &MockUploadAPI{ctrl: ctrl}
	mock.recorder = &MockUploadAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploadAPI) EXPECT() *MockUploadAPIMockRecorder {
	return m.recorder
}

// Upload mocks base method.
func (m *MockUploadAPI) Upload(ctx context.Context, uploadType model.UploadType, reader io.Reader, name string, size int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, uploadType, reader, name, size)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockUploadAPIMockRecorder) Upload(ctx, uploadType, reader, name, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockUploadAPI)(nil).Upload), ctx, uploadType, reader, name, size)
}
